/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,ts}",
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        'surface-elevated': 'var(--color-surface-elevated)',
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        primary: {
          DEFAULT: '#7C3AED',
          hover: '#8B5CF6',
          soft: 'rgba(124,58,237,0.12)',
          border: 'rgba(124,58,237,0.35)',
        },
        success: '#22C55E',
        warning: '#FACC15',
        error: '#EF4444',
        info: '#38BDF8',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-hero': ['72px', { lineHeight: '110%', letterSpacing: '-0.02em' }],
        'display': ['56px', { lineHeight: '110%', letterSpacing: '-0.02em' }],
        'h1': ['48px', { lineHeight: '120%', letterSpacing: '-0.01em' }],
        'h2': ['36px', { lineHeight: '120%', letterSpacing: '-0.01em' }],
        'h3': ['28px', { lineHeight: '120%', letterSpacing: '-0.01em' }],
        'h4': ['22px', { lineHeight: '120%', letterSpacing: '-0.01em' }],
        'body-lg': ['18px', { lineHeight: '160%' }],
        'body': ['16px', { lineHeight: '160%' }],
        'small': ['14px', { lineHeight: '150%' }],
        'caption': ['12px', { lineHeight: '150%' }],
        'tech-label': ['11px', { lineHeight: '150%', letterSpacing: '0.08em' }],
      },
      spacing: {
        '4': '4px',
        '8': '8px',
        '16': '16px',
        '24': '24px',
        '32': '32px',
        '40': '40px',
        '48': '48px',
        '56': '56px',
        '64': '64px',
        '80': '80px',
        '96': '96px',
        '120': '120px',
        '160': '160px',
      },
      borderRadius: {
        'button': '10px',
        'card': '12px',
        'panel': '12px',
        'input': '10px',
        'badge': '999px',
      },
      borderWidth: {
        'interactive': '1px',
        'strong': '2px',
        'focus': '2px',
      },
      opacity: {
        '10': '0.1',
        '20': '0.2',
        '40': '0.4',
        '60': '0.6',
        '80': '0.8',
      },
      transitionDuration: {
        'instant': '100ms',
        'fast': '150ms',
        'standard': '250ms',
        'slow': '400ms',
        'reveal': '600ms',
        'boot': '1800ms',
      },
      transitionTimingFunction: {
        'smooth': 'cubic-bezier(0.22,1,0.36,1)',
      },
      zIndex: {
        'background': '0',
        'grid': '10',
        'content': '20',
        'navigation': '30',
        'dropdown': '40',
        'modal': '50',
        'overlay': '60',
        'loading': '70',
        'cursor': '80',
      },
      maxWidth: {
        'small': '768px',
        'medium': '1024px',
        'large': '1280px',
        'maximum': '1440px',
      },
    },
  },
  plugins: [],
}
